// Copyright (C) 2026 Víctor Carreras
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:quizdy/domain/models/quiz/question.dart';
import 'package:quizdy/domain/models/quiz/study_chunk.dart';
import 'package:quizdy/domain/models/quiz/study_chunk_state.dart';
import 'package:quizdy/domain/models/quiz/study_component.dart';

/// Bundles localizable labels and pre-rendered LaTeX images needed during PDF
/// generation.
class _PdfContext {
  final String advantages;
  final String limitations;
  final String tableOfContents;
  final String questionsPageTitle;
  final String answersLabel;

  /// Maps raw equation strings to pre-rendered PNG bytes captured via
  /// [LaTeXImageRenderer]. When an entry is present the equation is embedded
  /// as an image instead of being converted to plain text.
  final Map<String, Uint8List> latexImages;

  const _PdfContext({
    required this.advantages,
    required this.limitations,
    required this.tableOfContents,
    this.questionsPageTitle = 'Questions',
    this.answersLabel = 'Answer',
    this.latexImages = const {},
  });
}

/// Generates a PDF document from study data.
///
/// This class is platform-independent and contains only the PDF generation
/// logic using the `pdf` package. Saving the result to disk is handled by
/// the platform-specific [StudyPdfExportService].
class StudyPdfGenerator {
  StudyPdfGenerator._();

  /// Generates a PDF document from the provided study data and returns the
  /// bytes of the resulting file.
  ///
  /// [advantagesLabel], [limitationsLabel] and [tableOfContentsLabel] are the
  /// localized strings used in the PDF. They default to English if omitted.
  static Future<Uint8List> generate({
    required String documentTitle,
    String? documentSummary,
    required List<StudyChunk> chunks,
    String advantagesLabel = 'Advantages',
    String limitationsLabel = 'Limitations',
    String tableOfContentsLabel = 'Table of Contents',
    Map<String, Uint8List> latexImages = const {},
    List<Question> questions = const [],
    bool includeAnswers = false,
    String questionsPageTitle = 'Questions',
    String answersLabel = 'Answer',
  }) async {
    final labels = _PdfContext(
      advantages: advantagesLabel,
      limitations: limitationsLabel,
      tableOfContents: tableOfContentsLabel,
      questionsPageTitle: questionsPageTitle,
      answersLabel: answersLabel,
      latexImages: latexImages,
    );

    final pdf = pw.Document();

    final img1 = await rootBundle.load('images/pictorial_mark.jpg');
    final imageBytes1 = img1.buffer.asUint8List();

    final img2 = await rootBundle.load('images/Quizdy.jpg');
    final imageBytes2 = img2.buffer.asUint8List();

    final pageTheme = pw.PageTheme(
      pageFormat: PdfPageFormat.a4,
      buildBackground: (context) => pw.Container(
        color: PdfColors.white,
        child: pw.Center(
          child: pw.Opacity(
            opacity: 0.1,
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Image(pw.MemoryImage(imageBytes1), height: 240),
                pw.Image(pw.MemoryImage(imageBytes2), height: 180),
              ],
            ),
          ),
        ),
      ),
      margin: const pw.EdgeInsets.symmetric(horizontal: 48, vertical: 40),
    );

    pw.Widget buildFooter(pw.Context context) => pw.Container(
      margin: const pw.EdgeInsets.only(top: 20),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Row(
            children: [
              pw.Image(pw.MemoryImage(imageBytes1), width: 18, height: 18),
              pw.SizedBox(width: 6),
              pw.Text(
                'Generated by Quizdy',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ),
          pw.Text(
            context.pageNumber.toString(),
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
        ],
      ),
    );

    final readyChunks = chunks
        .where(
          (c) =>
              c.status == StudyChunkState.completed ||
              c.status == StudyChunkState.downloaded,
        )
        .toList();

    // Page 1: Cover — full-page centered layout, no footer.
    pdf.addPage(
      pw.Page(
        pageTheme: pageTheme,
        build: (context) => _buildCoverSection(documentTitle, documentSummary),
      ),
    );

    // Pages 2+: Content — added before the TOC page so that pw.Outline
    // widgets register their PdfPage references before the TOC's postProcess.
    pdf.addPage(
      pw.MultiPage(
        pageTheme: pageTheme,
        footer: buildFooter,
        build: (pw.Context context) => _buildChunks(chunks, labels),
      ),
    );

    // TOC page: physically inserted at index 1 (right after the cover) but
    // added to the processing queue last so all Outline entries are resolved.
    // pw.TableOfContent uses DelayedWidget internally to read page numbers
    // after the full document outline is built.
    if (readyChunks.isNotEmpty || questions.isNotEmpty) {
      pdf.addPage(
        pw.Page(
          pageTheme: pageTheme,
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      labels.tableOfContents,
                      style: pw.TextStyle(
                        fontSize: 20,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Divider(thickness: 2, color: PdfColors.grey600),
                    pw.SizedBox(height: 16),
                    pw.TableOfContent(),
                  ],
                ),
              ),
              buildFooter(context),
            ],
          ),
        ),
        index: 1,
      );
    }

    // Questions page: appended at the end when requested.
    if (questions.isNotEmpty) {
      pdf.addPage(
        pw.MultiPage(
          pageTheme: pageTheme,
          footer: buildFooter,
          build: (pw.Context context) =>
              _buildQuestionsPage(questions, labels, latexImages),
        ),
      );
    }

    // Answers page: separate page after questions when requested.
    if (questions.isNotEmpty && includeAnswers) {
      pdf.addPage(
        pw.MultiPage(
          pageTheme: pageTheme,
          footer: buildFooter,
          build: (pw.Context context) =>
              _buildAnswersPage(questions, labels, latexImages),
        ),
      );
    }

    return pdf.save();
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  static List<pw.Widget> _buildQuestionsPage(
    List<Question> questions,
    _PdfContext labels,
    Map<String, Uint8List> latexImages,
  ) {
    final widgets = <pw.Widget>[
      pw.Outline(
        name: 'questions_section',
        title: labels.questionsPageTitle,
        level: 0,
        child: pw.Text(
          labels.questionsPageTitle,
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        ),
      ),
      pw.SizedBox(height: 8),
      pw.Divider(thickness: 2, color: PdfColors.grey600),
      pw.SizedBox(height: 16),
    ];

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 12),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                '${i + 1}. ${_strip(q.text)}',
                style:
                    pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
              ),
              ..._inlineEquationWidgets(q.text, latexImages),
              if (q.options.isNotEmpty) ...[
                pw.SizedBox(height: 4),
                ...List.generate(q.options.length, (j) {
                  final label = String.fromCharCode(65 + j); // A, B, C…
                  return pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Padding(
                        padding: const pw.EdgeInsets.only(left: 16, bottom: 2),
                        child: pw.Row(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text(
                              '$label. ',
                              style: const pw.TextStyle(fontSize: 10),
                            ),
                            pw.Expanded(
                              child: pw.Text(
                                _strip(q.options[j]),
                                style: const pw.TextStyle(fontSize: 10),
                              ),
                            ),
                          ],
                        ),
                      ),
                      ..._inlineEquationWidgets(
                        q.options[j],
                        latexImages,
                        paddingLeft: 32,
                      ),
                    ],
                  );
                }),
              ],
            ],
          ),
        ),
      );
    }

    return widgets;
  }

  static List<pw.Widget> _buildAnswersPage(
    List<Question> questions,
    _PdfContext labels,
    Map<String, Uint8List> latexImages,
  ) {
    final widgets = <pw.Widget>[
      pw.Outline(
        name: 'answers_section',
        title: labels.answersLabel,
        level: 0,
        child: pw.Text(
          labels.answersLabel,
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        ),
      ),
      pw.SizedBox(height: 8),
      pw.Divider(thickness: 2, color: PdfColors.grey600),
      pw.SizedBox(height: 16),
    ];

    for (int i = 0; i < questions.length; i++) {
      final q = questions[i];
      final correctLabels = q.correctAnswers
          .where((idx) => idx < q.options.length)
          .map(
            (idx) =>
                '${String.fromCharCode(65 + idx)}. ${_strip(q.options[idx])}',
          )
          .toList();

      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 10),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                '${i + 1}. ',
                style:
                    pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
              ),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      _strip(q.text),
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey700,
                      ),
                    ),
                    ..._inlineEquationWidgets(q.text, latexImages),
                    pw.SizedBox(height: 3),
                    if (correctLabels.isNotEmpty)
                      ...q.correctAnswers
                          .where((idx) => idx < q.options.length)
                          .expand((idx) => [
                            pw.Text(
                              '${String.fromCharCode(65 + idx)}. ${_strip(q.options[idx])}',
                              style: pw.TextStyle(
                                fontSize: 10,
                                fontWeight: pw.FontWeight.bold,
                                color: PdfColors.green800,
                              ),
                            ),
                            ..._inlineEquationWidgets(
                              q.options[idx],
                              latexImages,
                            ),
                          ])
                    else if (q.explanation.isNotEmpty) ...[
                      pw.Text(
                        _strip(q.explanation),
                        style: pw.TextStyle(
                          fontSize: 10,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.green800,
                        ),
                      ),
                      ..._inlineEquationWidgets(q.explanation, latexImages),
                    ],
                  ],
                ),
              ),
            ],
          ),
        ),
      );
    }

    return widgets;
  }

  /// Returns image widgets for any inline LaTeX equations found in [text] that
  /// have a pre-rendered entry in [latexImages]. Equations with no pre-rendered
  /// image are already shown as plain text via [_strip], so they are skipped.
  static List<pw.Widget> _inlineEquationWidgets(
    String text,
    Map<String, Uint8List> latexImages, {
    double paddingLeft = 0,
  }) {
    final widgets = <pw.Widget>[];
    final patterns = [
      RegExp(r'\$\$(.+?)\$\$', dotAll: true),
      RegExp(r'(?<!\$)\$(?!\$)(.+?)(?<!\$)\$(?!\$)', dotAll: true),
      RegExp(r'\\\[(.+?)\\\]', dotAll: true),
      RegExp(r'\\\((.+?)\\\)', dotAll: true),
    ];
    final seen = <String>{};
    for (final pattern in patterns) {
      for (final match in pattern.allMatches(text)) {
        final eq = match.group(1)?.trim() ?? '';
        if (eq.isEmpty || seen.contains(eq)) continue;
        seen.add(eq);
        final bytes = latexImages[eq];
        if (bytes == null) continue;
        widgets.add(
          pw.Padding(
            padding: pw.EdgeInsets.only(left: paddingLeft, top: 4, bottom: 4),
            child: pw.Center(child: pw.Image(pw.MemoryImage(bytes))),
          ),
        );
      }
    }
    return widgets;
  }

  static pw.Widget _buildCoverSection(String title, String? summary) {
    return pw.Center(
      child: pw.Column(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text(
            title,
            textAlign: pw.TextAlign.center,
            style: pw.TextStyle(fontSize: 40, fontWeight: pw.FontWeight.bold),
          ),
          if (summary != null && summary.isNotEmpty) ...[
            pw.SizedBox(height: 20),
            pw.SizedBox(
              width: 400,
              child: pw.Text(
                _strip(summary),
                textAlign: pw.TextAlign.center,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontStyle: pw.FontStyle.italic,
                  color: PdfColors.grey600,
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  static List<pw.Widget> _buildChunks(
    List<StudyChunk> chunks,
    _PdfContext labels,
  ) {
    final readyChunks = chunks
        .where(
          (c) =>
              c.status == StudyChunkState.completed ||
              c.status == StudyChunkState.downloaded,
        )
        .toList();

    final widgets = <pw.Widget>[];
    for (int i = 0; i < readyChunks.length; i++) {
      widgets.addAll(_buildChunk(readyChunks[i], i, labels));
    }
    return widgets;
  }

  static List<pw.Widget> _buildChunk(
    StudyChunk chunk,
    int index,
    _PdfContext labels,
  ) {
    final widgets = <pw.Widget>[];

    final chunkLabel = '${index + 1}. ${_strip(chunk.title)}';
    widgets.add(
      pw.Outline(
        name: 'chunk_$index',
        title: chunkLabel,
        level: 0,
        child: pw.Text(
          chunkLabel,
          style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
        ),
      ),
    );

    /* Note: AI summaries excluded
     if (chunk.aiSummary != null && chunk.aiSummary!.isNotEmpty) {
      widgets.add(pw.SizedBox(height: 4));
      widgets.add(
        pw.Text(
          _strip(chunk.aiSummary!),
          style: pw.TextStyle(
            fontSize: 11,
            fontStyle: pw.FontStyle.italic,
            color: PdfColors.grey700,
          ),
        ),
      );
    }
    */

    widgets.add(pw.SizedBox(height: 8));
    widgets.add(pw.Divider(color: PdfColors.grey400));
    widgets.add(pw.SizedBox(height: 8));

    for (final page in chunk.pages) {
      for (final component in page.uiElements) {
        widgets.addAll(_buildComponent(component, labels));
      }
    }

    widgets.add(pw.SizedBox(height: 16));

    return widgets;
  }

  static List<pw.Widget> _buildComponent(
    StudyComponent component,
    _PdfContext labels,
  ) {
    switch (component.componentType) {
      case StudyComponentType.sectionTitle:
        return _buildSectionTitle(component);
      case StudyComponentType.paragraph:
        return _buildParagraph(component);
      case StudyComponentType.keyDefinition:
        return _buildKeyDefinition(component);
      case StudyComponentType.numberedList:
        return _buildNumberedList(component);
      case StudyComponentType.comparisonTable:
        return _buildComparisonTable(component);
      case StudyComponentType.quote:
        return _buildQuote(component);
      case StudyComponentType.warning:
        return _buildWarning(component);
      case StudyComponentType.formula:
        return _buildFormula(component, labels);
      case StudyComponentType.timeline:
        return _buildTimeline(component);
      case StudyComponentType.prosCons:
        return _buildProsCons(component, labels);
      case StudyComponentType.keyConcepts:
        return _buildKeyConcepts(component);
      case StudyComponentType.reminder:
        return _buildReminder(component);
      case StudyComponentType.iconCards:
        return _buildIconCards(component);
    }
  }

  // ---
  // Component renderers
  // ---

  static List<pw.Widget> _buildSectionTitle(StudyComponent c) {
    final title = c.props['title']?.toString() ?? '';
    final subtitle = c.props['subtitle']?.toString();
    return [
      pw.SizedBox(height: 6),
      pw.Text(
        _strip(title),
        style: pw.TextStyle(fontSize: 15, fontWeight: pw.FontWeight.bold),
      ),
      if (subtitle != null && subtitle.isNotEmpty)
        pw.Text(
          _strip(subtitle),
          style: pw.TextStyle(
            fontSize: 12,
            fontStyle: pw.FontStyle.italic,
            color: PdfColors.grey700,
          ),
        ),
      pw.Divider(color: PdfColors.grey400),
      pw.SizedBox(height: 4),
    ];
  }

  static List<pw.Widget> _buildParagraph(StudyComponent c) {
    final title = c.props['title']?.toString();
    final body = c.props['body']?.toString() ?? '';
    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      if (body.isNotEmpty)
        pw.Padding(
          padding: const pw.EdgeInsets.only(top: 4, bottom: 10),
          child: pw.Text(_strip(body), style: const pw.TextStyle(fontSize: 11)),
        ),
    ];
  }

  static List<pw.Widget> _buildKeyDefinition(StudyComponent c) {
    final term = c.props['term']?.toString() ?? '';
    final body = c.props['body']?.toString() ?? '';
    return [
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            '${_strip(term)}: ',
            style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
          ),
          pw.Expanded(
            child: pw.Text(
              _strip(body),
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 6),
    ];
  }

  static List<pw.Widget> _buildNumberedList(StudyComponent c) {
    final title = c.props['title']?.toString();
    final rawItems = c.props['items'] as List<dynamic>? ?? [];
    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      ...List.generate(rawItems.length, (i) {
        final item = rawItems[i];
        final String itemTitle;
        final String? itemDescription;
        if (item is Map) {
          itemTitle = _strip(item['title']?.toString() ?? '');
          final desc = item['description']?.toString() ?? '';
          itemDescription = desc.isNotEmpty ? _strip(desc) : null;
        } else {
          itemTitle = _strip(item.toString());
          itemDescription = null;
        }
        return pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 6),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                '${i + 1}. ',
                style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    if (itemTitle.isNotEmpty)
                      pw.Text(
                        itemTitle,
                        style: pw.TextStyle(
                          fontSize: 11,
                          fontWeight: itemDescription != null
                              ? pw.FontWeight.bold
                              : pw.FontWeight.normal,
                        ),
                      ),
                    if (itemDescription != null)
                      pw.Text(
                        itemDescription,
                        style: const pw.TextStyle(fontSize: 11),
                      ),
                  ],
                ),
              ),
            ],
          ),
        );
      }),
      pw.SizedBox(height: 6),
    ];
  }

  static List<pw.Widget> _buildComparisonTable(StudyComponent c) {
    final title = c.props['title']?.toString();
    final rawColumns = (c.props['columns'] as List<dynamic>? ?? [])
        .map((e) => e.toString())
        .toList();
    final rawRows = c.props['rows'] as List<dynamic>? ?? [];

    final rows = rawRows.map((row) {
      if (row is Map<String, dynamic>) {
        final label = row['label']?.toString() ?? '';
        final values = (row['values'] as List<dynamic>? ?? [])
            .map((e) => e.toString())
            .toList();
        return {'label': label, 'values': values};
      }
      return {'label': '', 'values': <String>[]};
    }).toList();

    if (rawColumns.isEmpty && rows.isEmpty) return [];

    // Build header row + data rows
    final headerCells = rawColumns.map((col) {
      return pw.Container(
        color: PdfColors.grey300,
        padding: const pw.EdgeInsets.all(6),
        child: pw.Text(
          _strip(col),
          style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
        ),
      );
    }).toList();

    final tableRows = <pw.TableRow>[];

    if (headerCells.isNotEmpty) {
      tableRows.add(pw.TableRow(children: headerCells));
    }

    for (final row in rows) {
      final label = row['label'] as String? ?? '';
      final values = row['values'] as List<String>? ?? [];
      final cells = <pw.Widget>[];
      if (label.isNotEmpty || rawColumns.length > values.length) {
        cells.add(
          pw.Padding(
            padding: const pw.EdgeInsets.all(6),
            child: pw.Text(
              _strip(label),
              style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold),
            ),
          ),
        );
      }
      for (final v in values) {
        cells.add(
          pw.Padding(
            padding: const pw.EdgeInsets.all(6),
            child: pw.Text(_strip(v), style: const pw.TextStyle(fontSize: 10)),
          ),
        );
      }
      if (cells.isNotEmpty) {
        tableRows.add(pw.TableRow(children: cells));
      }
    }

    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      if (tableRows.isNotEmpty)
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
          children: tableRows,
        ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildQuote(StudyComponent c) {
    final body = c.props['body']?.toString() ?? '';
    final author = c.props['author']?.toString();
    return [
      pw.Container(
        decoration: const pw.BoxDecoration(
          border: pw.Border(
            left: pw.BorderSide(color: PdfColors.grey500, width: 3),
          ),
        ),
        padding: const pw.EdgeInsets.only(left: 12, top: 4, bottom: 4),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              '"${_strip(body)}"',
              style: pw.TextStyle(fontSize: 12, fontStyle: pw.FontStyle.italic),
            ),
            if (author != null && author.isNotEmpty) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                '- ${_strip(author)}',
                textAlign: pw.TextAlign.right,
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey700,
                ),
              ),
            ],
          ],
        ),
      ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildWarning(StudyComponent c) {
    final body = c.props['body']?.toString() ?? '';
    return [
      pw.Container(
        decoration: pw.BoxDecoration(
          color: PdfColors.orange50,
          border: pw.Border.all(color: PdfColors.orange, width: 0.5),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        padding: const pw.EdgeInsets.all(10),
        child: pw.Text(
          _strip(body),
          style: const pw.TextStyle(fontSize: 11, color: PdfColors.orange900),
        ),
      ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildFormula(StudyComponent c, _PdfContext ctx) {
    final title = c.props['title']?.toString();
    final equation = c.props['equation']?.toString() ?? '';
    final equationLabel = c.props['equation_label']?.toString();
    final body = c.props['body']?.toString();
    final equationBytes = ctx.latexImages[equation];
    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      if (equation.isNotEmpty)
        pw.Container(
          color: PdfColors.grey100,
          padding: const pw.EdgeInsets.all(10),
          child: equationBytes != null
              ? pw.Center(child: pw.Image(pw.MemoryImage(equationBytes)))
              : pw.Text(
                  _latexToText(equation),
                  style: pw.TextStyle(fontSize: 13, font: pw.Font.courier()),
                ),
        ),
      if (equation.isNotEmpty) ...[
        pw.Center(
          child: pw.Text(
            _strip(equation),
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
            textAlign: pw.TextAlign.center,
          ),
        ),
        pw.SizedBox(height: 6),
      ],
      if (equationLabel != null && equationLabel.isNotEmpty) ...[
        pw.Text(
          _strip(equationLabel),
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 6),
      ],
      if (body != null && body.isNotEmpty)
        pw.Text(_strip(body), style: const pw.TextStyle(fontSize: 11)),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildTimeline(StudyComponent c) {
    final title = c.props['title']?.toString();
    final rawItems = c.props['items'] as List<dynamic>? ?? [];
    final items = rawItems.map((item) {
      if (item is Map<String, dynamic>) {
        return {
          'date': item['date']?.toString() ?? '',
          'title': item['title']?.toString() ?? '',
          'description': item['description']?.toString() ?? '',
        };
      }
      return {'date': '', 'title': item.toString(), 'description': ''};
    }).toList();

    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      ...items.map((item) {
        final date = item['date'] ?? '';
        final itemTitle = item['title'] ?? '';
        final description = item['description'] ?? '';
        return pw.Padding(
          padding: const pw.EdgeInsets.only(left: 16, bottom: 8),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                children: [
                  if (date.isNotEmpty) ...[
                    pw.Text(
                      '[$date] ',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                  pw.Expanded(
                    child: pw.Text(
                      _strip(itemTitle),
                      style: pw.TextStyle(
                        fontSize: 11,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
              if (description.isNotEmpty)
                pw.Text(
                  _strip(description),
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey700,
                  ),
                ),
            ],
          ),
        );
      }),
      pw.SizedBox(height: 6),
    ];
  }

  static List<pw.Widget> _buildProsCons(StudyComponent c, _PdfContext labels) {
    final items = c.props['items'] as Map<String, dynamic>?;
    final pros = (items?['pros'] as List<dynamic>? ?? [])
        .map((e) => _strip(_itemToText(e)))
        .toList();
    final cons = (items?['cons'] as List<dynamic>? ?? [])
        .map((e) => _strip(_itemToText(e)))
        .toList();

    pw.Widget buildColumn(String header, List<String> list, PdfColor color) {
      return pw.Expanded(
        child: pw.Container(
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: color, width: 0.5),
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
          ),
          padding: const pw.EdgeInsets.all(8),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                header,
                style: pw.TextStyle(
                  fontSize: 11,
                  fontWeight: pw.FontWeight.bold,
                  color: color,
                ),
              ),
              pw.SizedBox(height: 6),
              ...list.map(
                (item) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 4),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        '- ',
                        style: pw.TextStyle(fontSize: 11, color: color),
                      ),
                      pw.Expanded(
                        child: pw.Text(
                          item,
                          style: pw.TextStyle(fontSize: 11, color: color),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      );
    }

    return [
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          buildColumn(labels.advantages, pros, PdfColors.green700),
          pw.SizedBox(width: 10),
          buildColumn(labels.limitations, cons, PdfColors.red700),
        ],
      ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildKeyConcepts(StudyComponent c) {
    final title = c.props['title']?.toString();
    final rawItems = c.props['items'] as List<dynamic>? ?? [];
    // For chips only show the title/label — description would overflow.
    final items = rawItems.map((e) => _strip(_itemLabel(e))).toList();
    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      pw.Wrap(
        spacing: 6,
        runSpacing: 6,
        children: items
            .map(
              (concept) => pw.Container(
                padding: const pw.EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: 4,
                ),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.blue400, width: 0.5),
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(12),
                  ),
                ),
                child: pw.Text(
                  concept,
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.blue800,
                  ),
                ),
              ),
            )
            .toList(),
      ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildReminder(StudyComponent c) {
    final body = c.props['body']?.toString() ?? '';
    return [
      pw.Container(
        decoration: pw.BoxDecoration(
          color: PdfColors.blue50,
          border: pw.Border.all(color: PdfColors.blue300, width: 0.5),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        padding: const pw.EdgeInsets.all(10),
        child: pw.Text(
          _strip(body),
          style: const pw.TextStyle(fontSize: 11, color: PdfColors.blue900),
        ),
      ),
      pw.SizedBox(height: 10),
    ];
  }

  static List<pw.Widget> _buildIconCards(StudyComponent c) {
    final title = c.props['title']?.toString();
    final rawItems = c.props['items'] as List<dynamic>? ?? [];
    final items = rawItems.map((item) {
      if (item is Map<String, dynamic>) {
        return {
          'title': item['title']?.toString() ?? '',
          'description': item['description']?.toString() ?? '',
        };
      }
      return {'title': item.toString(), 'description': ''};
    }).toList();

    return [
      if (title != null && title.isNotEmpty)
        pw.Text(
          _strip(title),
          style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
        ),
      pw.SizedBox(height: 4),
      ...items.map((item) {
        final cardTitle = item['title'] ?? '';
        final description = item['description'] ?? '';
        return pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 6),
          child: pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            padding: const pw.EdgeInsets.all(8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (cardTitle.isNotEmpty)
                  pw.Text(
                    _strip(cardTitle),
                    style: pw.TextStyle(
                      fontSize: 11,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                if (description.isNotEmpty)
                  pw.Text(
                    _strip(description),
                    style: const pw.TextStyle(fontSize: 10),
                  ),
              ],
            ),
          ),
        );
      }),
      pw.SizedBox(height: 6),
    ];
  }

  // ---------------------------------------------------------------------------
  // Item text helpers
  // ---------------------------------------------------------------------------

  /// Returns a combined readable string from a list item that may be either a
  /// plain string or a Map with `title` / `description` / `label` keys.
  /// Used for pros/cons lists and other flat item lists.
  static String _itemToText(dynamic item) {
    if (item is Map) {
      final title =
          item['title']?.toString() ?? item['label']?.toString() ?? '';
      final desc = item['description']?.toString() ?? '';
      if (title.isNotEmpty && desc.isNotEmpty) return '$title: $desc';
      return title.isNotEmpty ? title : desc;
    }
    return item.toString();
  }

  /// Returns only the label/title portion of an item — for compact widgets
  /// like chips where description would overflow.
  static String _itemLabel(dynamic item) {
    if (item is Map) {
      return item['title']?.toString() ??
          item['label']?.toString() ??
          item['name']?.toString() ??
          item.toString();
    }
    return item.toString();
  }

  // ---------------------------------------------------------------------------
  // Markdown stripper
  // ---------------------------------------------------------------------------

  /// Strips Markdown and LaTeX delimiters from [text] so it renders cleanly
  /// in PDF. LaTeX math content is converted to readable Unicode via
  /// [_latexToText].
  static String _strip(String text) {
    final stripped = text
        // LaTeX: display mode $$...$$ must come before inline $...$
        .replaceAllMapped(
          RegExp(r'\$\$(.+?)\$\$', dotAll: true),
          (m) => _latexToText(m.group(1)!),
        )
        // LaTeX: inline $...$
        .replaceAllMapped(
          RegExp(r'\$(.+?)\$', dotAll: true),
          (m) => _latexToText(m.group(1)!),
        )
        // LaTeX: \(...\) inline
        .replaceAllMapped(
          RegExp(r'\\\((.+?)\\\)', dotAll: true),
          (m) => _latexToText(m.group(1)!),
        )
        // LaTeX: \[...\] display
        .replaceAllMapped(
          RegExp(r'\\\[(.+?)\\\]', dotAll: true),
          (m) => _latexToText(m.group(1)!),
        )
        // Markdown: **bold** and __bold__
        .replaceAllMapped(
          RegExp(r'\*\*(.+?)\*\*', dotAll: true),
          (m) => m.group(1)!,
        )
        .replaceAllMapped(
          RegExp(r'__(.+?)__', dotAll: true),
          (m) => m.group(1)!,
        )
        // Markdown: *italic* — use word-boundary-aware pattern to avoid
        // conflicting with underscores produced by LaTeX subscript conversion.
        .replaceAllMapped(
          RegExp(r'\*(.+?)\*', dotAll: true),
          (m) => m.group(1)!,
        )
        // Markdown: `code`
        .replaceAllMapped(RegExp(r'`(.+?)`', dotAll: true), (m) => m.group(1)!)
        // Markdown: [text](url)
        .replaceAllMapped(RegExp(r'\[(.+?)\]\(.+?\)'), (m) => m.group(1)!)
        // Markdown: # headings
        .replaceAll(RegExp(r'^#{1,6}\s+', multiLine: true), '');
    return _sanitizeUnicode(stripped.trim());
  }

  // ---------------------------------------------------------------------------
  // Unicode sanitizer
  // ---------------------------------------------------------------------------

  /// Replaces non-Latin-1 Unicode characters that appear bare in AI-generated
  /// text (i.e. outside LaTeX delimiters) with ASCII/Latin-1 equivalents safe
  /// for Helvetica / built-in PDF fonts.
  static String _sanitizeUnicode(String text) {
    const replacements = <String, String>{
      // Math operators
      '≠': '!=',
      '≤': '<=',
      '≥': '>=',
      '≈': '~',
      '≡': '===',
      '≪': '<<',
      '≫': '>>',
      '∝': '~',
      '∓': '-/+',
      // Arrows
      '→': '->',
      '←': '<-',
      '↑': '^',
      '↓': 'v',
      '↔': '<->',
      '⇒': '=>',
      '⇐': '<=',
      '⇔': '<=>',
      '⟹': '=>',
      '⟺': '<=>',
      // Math symbols
      '√': 'sqrt',
      '∞': 'inf',
      '∑': 'sum',
      '∏': 'prod',
      '∫': 'int',
      '∂': 'd',
      '∆': 'delta',
      '∇': 'grad',
      '∈': 'in',
      '∉': 'not in',
      '∋': 'contains',
      '⊂': 'subset',
      '⊃': 'superset',
      '⊆': 'subset=',
      '⊇': 'superset=',
      '∪': 'union',
      '∩': 'intersect',
      '∅': '{}',
      '∧': 'and',
      '∨': 'or',
      '¬': 'not',
      '⊕': 'xor',
      '⊗': 'x',
      '∀': 'for all',
      '∃': 'exists',
      '∄': 'not exists',
      '∴': 'therefore',
      '∵': 'because',
      '‖': '||',
      '⌊': 'floor(',
      '⌋': ')',
      '⌈': 'ceil(',
      '⌉': ')',
      // Superscript digits
      '⁰': '^0',
      '¹': '^1',
      '²': '^2',
      '³': '^3',
      '⁴': '^4',
      '⁵': '^5',
      '⁶': '^6',
      '⁷': '^7',
      '⁸': '^8',
      '⁹': '^9',
      // Subscript digits
      '₀': '_0',
      '₁': '_1',
      '₂': '_2',
      '₃': '_3',
      '₄': '_4',
      '₅': '_5',
      '₆': '_6',
      '₇': '_7',
      '₈': '_8',
      '₉': '_9',
      // Greek uppercase
      'Α': 'Alpha',
      'Β': 'Beta',
      'Γ': 'Gamma',
      'Δ': 'Delta',
      'Ε': 'Epsilon',
      'Ζ': 'Zeta',
      'Η': 'Eta',
      'Θ': 'Theta',
      'Ι': 'Iota',
      'Κ': 'Kappa',
      'Λ': 'Lambda',
      'Μ': 'Mu',
      'Ν': 'Nu',
      'Ξ': 'Xi',
      'Ο': 'Omicron',
      'Π': 'Pi',
      'Ρ': 'Rho',
      'Σ': 'Sigma',
      'Τ': 'Tau',
      'Υ': 'Upsilon',
      'Φ': 'Phi',
      'Χ': 'Chi',
      'Ψ': 'Psi',
      'Ω': 'Omega',
      // Greek lowercase
      'α': 'alpha',
      'β': 'beta',
      'γ': 'gamma',
      'δ': 'delta',
      'ε': 'epsilon',
      'ζ': 'zeta',
      'η': 'eta',
      'θ': 'theta',
      'ι': 'iota',
      'κ': 'kappa',
      'λ': 'lambda',
      'μ': 'mu',
      'ν': 'nu',
      'ξ': 'xi',
      'ο': 'omicron',
      'π': 'pi',
      'ρ': 'rho',
      'σ': 'sigma',
      'τ': 'tau',
      'υ': 'upsilon',
      'φ': 'phi',
      'χ': 'chi',
      'ψ': 'psi',
      'ω': 'omega',
      // Blackboard bold
      'ℝ': 'R',
      'ℕ': 'N',
      'ℤ': 'Z',
      'ℚ': 'Q',
      'ℂ': 'C',
      'ℙ': 'P',
      // Misc typographic
      '\u2212': '-', // minus sign
      '\u2215': '/', // division slash
      '\u22C5': '*', // dot operator
      '\u00B7': '*', // middle dot (Latin-1 but keep for clarity)
      '\u2014': '--', // em dash
      '\u2013': '-', // en dash
      '\u2026': '...', // ellipsis
      '\u00D7': 'x', // multiplication sign × (Latin-1, already supported, keep)
    };

    var result = text;
    for (final entry in replacements.entries) {
      if (result.contains(entry.key)) {
        result = result.replaceAll(entry.key, entry.value);
      }
    }

    // Final pass: drop any remaining characters outside Latin-1 (U+0100..U+FFFF)
    result = result.replaceAll(RegExp(r'[^\x00-\xFF]'), '?');

    return result;
  }

  // ---------------------------------------------------------------------------
  // LaTeX → ASCII-safe text converter
  // ---------------------------------------------------------------------------

  /// Converts LaTeX math notation to a plain-text representation that is safe
  /// to render with the PDF package's built-in fonts.
  ///
  /// The built-in PDF fonts (Helvetica, Courier, Times) use WinAnsi / Latin-1
  /// encoding. Characters outside that range (Greek letters, math symbols like
  /// √, →, ∞, etc.) render as boxes. This converter therefore maps everything
  /// that is not in Latin-1 to a recognisable ASCII / Latin-1 equivalent:
  ///   • \sqrt{x}       → sqrt(x)
  ///   • \frac{a}{b}    → (a / b)
  ///   • \rightarrow    → ->
  ///   • \alpha         → alpha
  ///   • \leq           → <=
  ///
  /// Latin-1 characters that ARE supported by the built-in fonts are kept as
  /// Unicode: ± × ÷ · ¬ µ ° etc.
  ///
  /// Nested constructs (e.g. \frac{\sqrt{x}}{2}) are resolved by running
  /// structural replacements in up to [_kMaxPasses] passes.
  static const int _kMaxPasses = 5;

  static String _latexToText(String latex) {
    var s = latex;

    // -- 1. Strip outer math delimiters that may have been passed through. ---
    s = s
        .replaceAllMapped(
          RegExp(r'\$\$(.+?)\$\$', dotAll: true),
          (m) => m.group(1)!,
        )
        .replaceAllMapped(
          RegExp(r'\$(.+?)\$', dotAll: true),
          (m) => m.group(1)!,
        )
        .replaceAllMapped(
          RegExp(r'\\\((.+?)\\\)', dotAll: true),
          (m) => m.group(1)!,
        )
        .replaceAllMapped(
          RegExp(r'\\\[(.+?)\\\]', dotAll: true),
          (m) => m.group(1)!,
        );

    // -- 2. LaTeX environments: \begin{env}...\end{env} → content only. ------
    s = s.replaceAllMapped(
      RegExp(r'\\begin\{[^}]*\}([\s\S]*?)\\end\{[^}]*\}'),
      (m) => m.group(1)!.trim(),
    );

    // -- 3. LaTeX line breaks \\ → space. ------------------------------------
    s = s.replaceAll(r'\\', ' ');

    // -- 4. Content-preserving wrappers: keep inner text, drop command. ------
    s = s.replaceAllMapped(
      RegExp(
        r'\\(?:text|mathrm|mathbf|mathit|mathsf|mathtt|mathcal|operatorname)\{([^{}]*)\}',
      ),
      (m) => m.group(1)!,
    );

    // -- 5. \mathbb{R} → R, \mathbb{N} → N, etc. (just the letter). ---------
    s = s.replaceAllMapped(RegExp(r'\\mathbb\{([^}]*)\}'), (m) => m.group(1)!);

    // -- 6. Accent/decoration commands: preserve the base, drop decoration. --
    //    PDF fonts have no combining-character support, so we just keep the
    //    inner content (x_hat → x, x_bar → x).  A label suffix is added for
    //    the most important ones to retain meaning.
    s = s.replaceAllMapped(
      RegExp(
        r'\\(?:hat|bar|overline|tilde|vec|dot|ddot|acute|grave)\{([^{}]*)\}',
      ),
      (m) => m.group(1)!,
    );

    // -- 7. Structural constructs — multiple passes handle nesting. ----------
    for (int pass = 0; pass < _kMaxPasses; pass++) {
      final before = s;

      // \frac{num}{den} → (num / den)
      s = s.replaceAllMapped(
        RegExp(r'\\frac\{([^{}]*)\}\{([^{}]*)\}'),
        (m) => '(${m.group(1)!} / ${m.group(2)!})',
      );

      // \sqrt[n]{x} → root_n(x)
      s = s.replaceAllMapped(
        RegExp(r'\\sqrt\[([^\]]*)\]\{([^{}]*)\}'),
        (m) => 'root${m.group(1)!}(${m.group(2)!})',
      );

      // \sqrt{x} → sqrt(x)
      s = s.replaceAllMapped(
        RegExp(r'\\sqrt\{([^{}]*)\}'),
        (m) => 'sqrt(${m.group(1)!})',
      );

      // ^{...} → ^(...) — keeps exponent notation readable
      s = s.replaceAllMapped(
        RegExp(r'\^\{([^{}]*)\}'),
        (m) => '^(${m.group(1)!})',
      );

      // _{...} → [subscript] — square brackets are universally readable
      s = s.replaceAllMapped(
        RegExp(r'_\{([^{}]*)\}'),
        (m) => '[${m.group(1)!}]',
      );

      if (s == before) break;
    }

    // -- 8. Bare single-character sub/superscripts (no braces): x_i, CO_2 --
    //    Only match a single alphanumeric char to avoid over-consuming text.
    s = s.replaceAllMapped(
      RegExp(r'_([a-zA-Z0-9])'),
      (m) => '[${m.group(1)!}]',
    );
    // Bare superscripts like x^2 are already readable — leave them as-is.

    // -- 9. Size modifiers before brackets: \left, \right, \big, \Big, etc. --
    s = s.replaceAll(RegExp(r'\\(?:left|right|[bB]ig{1,2})\s*'), '');

    // -- 10. Named LaTeX commands → ASCII-safe text. -------------------------
    //
    //  IMPORTANT: All target strings must use only Latin-1 / WinAnsi
    //  characters so they render correctly with the built-in PDF fonts.
    //  Characters ≤ U+00FF that ARE in WinAnsi are used where appropriate
    //  (±, ×, ÷, ·, ¬, µ, °).  Everything else uses ASCII.
    //
    //  Order matters: longer keys before their common prefixes
    //  (e.g. \varepsilon before \epsilon, \Leftrightarrow before \leftarrow).
    const symbols = <String, String>{
      // Greek – variant forms first
      r'\varepsilon': 'eps',
      r'\varphi': 'phi',
      r'\vartheta': 'theta',
      r'\varrho': 'rho',
      r'\varsigma': 'sigma',
      // Greek – lowercase
      r'\alpha': 'alpha',
      r'\beta': 'beta',
      r'\gamma': 'gamma',
      r'\delta': 'delta',
      r'\epsilon': 'eps',
      r'\zeta': 'zeta',
      r'\eta': 'eta',
      r'\theta': 'theta',
      r'\iota': 'iota',
      r'\kappa': 'kappa',
      r'\lambda': 'lambda',
      r'\mu': 'mu', // µ (U+00B5) is Latin-1 but confusable; keep ASCII
      r'\nu': 'nu',
      r'\xi': 'xi',
      r'\pi': 'pi',
      r'\rho': 'rho',
      r'\sigma': 'sigma',
      r'\tau': 'tau',
      r'\upsilon': 'upsilon',
      r'\phi': 'phi',
      r'\chi': 'chi',
      r'\psi': 'psi',
      r'\omega': 'omega',
      // Greek – uppercase
      r'\Gamma': 'Gamma',
      r'\Delta': 'Delta',
      r'\Theta': 'Theta',
      r'\Lambda': 'Lambda',
      r'\Xi': 'Xi',
      r'\Pi': 'Pi',
      r'\Sigma': 'Sigma',
      r'\Upsilon': 'Upsilon',
      r'\Phi': 'Phi',
      r'\Psi': 'Psi',
      r'\Omega': 'Omega',
      // Large operators
      r'\sum': 'sum',
      r'\prod': 'prod',
      r'\coprod': 'coprod',
      r'\iint': 'iint',
      r'\iiint': 'iiint',
      r'\oint': 'oint',
      r'\int': 'int',
      r'\partial': 'd', // partial derivative → plain d in context
      r'\nabla': 'grad',
      // Trig / common functions — already ASCII, just strip the backslash
      r'\arccos': 'arccos',
      r'\arcsin': 'arcsin',
      r'\arctan': 'arctan',
      r'\sinh': 'sinh',
      r'\cosh': 'cosh',
      r'\tanh': 'tanh',
      r'\coth': 'coth',
      r'\sin': 'sin',
      r'\cos': 'cos',
      r'\tan': 'tan',
      r'\cot': 'cot',
      r'\sec': 'sec',
      r'\csc': 'csc',
      r'\limsup': 'lim sup',
      r'\liminf': 'lim inf',
      r'\lim': 'lim',
      r'\sup': 'sup',
      r'\inf': 'inf',
      r'\max': 'max',
      r'\min': 'min',
      r'\log': 'log',
      r'\ln': 'ln',
      r'\exp': 'exp',
      r'\det': 'det',
      r'\dim': 'dim',
      r'\ker': 'ker',
      r'\deg': 'deg',
      r'\gcd': 'gcd',
      r'\lcm': 'lcm',
      r'\mod': 'mod',
      r'\arg': 'arg',
      // Misc symbols — Latin-1 where available, ASCII otherwise
      r'\infty': 'inf',
      r'\varnothing': '{}',
      r'\emptyset': '{}',
      r'\pm': '\u00b1', // ± Latin-1 U+00B1 ✓
      r'\mp': '-/+',
      r'\times': '\u00d7', // × Latin-1 U+00D7 ✓
      r'\div': '\u00f7', // ÷ Latin-1 U+00F7 ✓
      r'\cdots': '...',
      r'\cdot': '\u00b7', // · Latin-1 U+00B7 ✓
      r'\ldots': '...',
      r'\vdots': ':',
      r'\ddots': '...',
      // Comparison operators → ASCII pairs
      r'\leq': '<=',
      r'\geq': '>=',
      r'\ll': '<<',
      r'\gg': '>>',
      r'\neq': '!=',
      r'\approx': '~=',
      r'\cong': '~=',
      r'\equiv': '===',
      r'\sim': '~',
      r'\simeq': '~=',
      r'\propto': 'prop',
      // Set operators → ASCII / short words
      r'\notin': 'not in',
      r'\in': 'in',
      r'\ni': 'contains',
      r'\subseteq': 'subset=',
      r'\supseteq': 'supset=',
      r'\subset': 'subset',
      r'\supset': 'supset',
      r'\cup': 'union',
      r'\cap': 'inter',
      r'\setminus': '\\',
      // Logic
      r'\forall': 'forall',
      r'\nexists': '!exists',
      r'\exists': 'exists',
      r'\neg': '\u00ac', // ¬ Latin-1 U+00AC ✓
      r'\land': 'and',
      r'\lor': 'or',
      r'\oplus': '(+)',
      r'\otimes': '(x)',
      // Arrows → ASCII
      r'\Leftrightarrow': '<=>',
      r'\Rightarrow': '=>',
      r'\Leftarrow': '<=',
      r'\leftrightarrow': '<->',
      r'\rightarrow': '->',
      r'\leftarrow': '<-',
      r'\mapsto': '|->',
      r'\to': '->',
      r'\uparrow': '^',
      r'\downarrow': 'v',
      r'\updownarrow': '^v',
      // Brackets → ASCII equivalents
      r'\langle': '<',
      r'\rangle': '>',
      r'\lfloor': 'floor(',
      r'\rfloor': ')',
      r'\lceil': 'ceil(',
      r'\rceil': ')',
      r'\|': '||',
      // Escaped punctuation
      r'\{': '{',
      r'\}': '}',
      r'\%': '%',
      r'\#': '#',
      r'\&': '&',
      // Physics / misc
      r'\hbar': 'hbar',
      r'\ell': 'l',
      r'\Re': 'Re',
      r'\Im': 'Im',
      r'\aleph': 'aleph',
    };

    for (final entry in symbols.entries) {
      s = s.replaceAll(entry.key, entry.value);
    }

    // -- 11. Strip remaining unknown LaTeX commands. -------------------------
    s = s.replaceAll(RegExp(r'\\[a-zA-Z]+\*?\s*'), '');

    // -- 12. Remove leftover bare braces. ------------------------------------
    s = s.replaceAll('{', '').replaceAll('}', '');

    // -- 13. Collapse multiple spaces. ---------------------------------------
    s = s.replaceAll(RegExp(r'  +'), ' ');

    return s.trim();
  }
}
