// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:quizdy/domain/models/srs/srs_metadata.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SrsMetadataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SrsMetadataAdapter());
  }
}
