name: quiz-app
version: "1.0.0"
summary: Quiz App
description: |
  A Quiz application that provides an interactive and engaging quiz experience.
base: core24
confinement: strict
grade: stable

apps:
  quiz-app:
    command: quiz_app
    extensions: [gnome]
    plugs:
      - network
      - home
    # desktop file is provided under meta/gui so snapd can publish it
    desktop: meta/gui/quiz-app.desktop

parts:
  quiz-app:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-environment:
      - PUB_CACHE: "$SNAPCRAFT_PART_BUILD/.pub-cache"

  desktop-assets:
    plugin: dump
    source: snap
    organize:
      gui/quiz-app.desktop: meta/gui/quiz-app.desktop
      gui/quiz-app.png: meta/gui/icons/hicolor/256x256/apps/quiz-app.png
      gui/application-x-quiz.png: meta/gui/icons/hicolor/256x256/mimetypes/application-x-quiz.png
      local/x-quiz.xml: meta/gui/mime/packages/x-quiz.xml
