name: Publish Snap to Snapcraft
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish_linux_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config liblzma-dev libstdc++-12-dev libgtk-3-dev
      - name: Build snap
        uses: canonical/action-build@v1
        with:
          path: snap
      - name: Authenticate to Snapcraft
        run: sudo snapcraft login --with ${{ secrets.SNAPCRAFT_LOGIN }}
      - name: Publish to Snap Store
        run: sudo snapcraft upload quiz-app.snap --release=stable
        working-directory: snap
