name: Publish Microsoft Store
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish_windows_release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: microsoft/setup-msstore-cli@v1.1
      - run: msstore reconfigure --tenantId ${{ secrets.PARTNER_CENTER_TENANT_ID }} --sellerId ${{ secrets.PARTNER_CENTER_SELLER_ID }} --clientId ${{ secrets.PARTNER_CENTER_CLIENT_ID }} --clientSecret ${{ secrets.PARTNER_CENTER_CLIENT_SECRET }}
      
      - name: Install Dart dependencies
        run: flutter pub get

      - name: Create MSIX package
        run: msstore package .

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
