name: Publish Snap to Snapcraft
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish_linux_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config liblzma-dev libstdc++-12-dev libgtk-3-dev
      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic
      - name: Install core22 snap
        run: sudo snap install core22 --channel=latest/stable
      - name: Build Flutter Linux app
        run: flutter build linux
      - name: Build snap
        run: snapcraft pack --debug --destructive-mode
      - name: Publish to Snap Store
        run: snapcraft upload quiz-app*.snap --release=stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
